import { jsPDF } from "jspdf";
import type { StartupBlueprint } from "./ai.functions";

export type ReportMeta = {
  name: string;
  score: number | null;
  createdAt: string;
};

function fmtDate(ts: string) {
  return new Date(ts).toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function asList(v: unknown): string[] {
  if (Array.isArray(v)) return v.map(String).filter(Boolean);
  if (typeof v === "string" && v.trim()) return [v];
  return [];
}

function asText(v: unknown): string {
  if (!v) return "";
  if (typeof v === "string") return v;
  if (Array.isArray(v)) return v.map(String).join(", ");
  return String(v);
}

type Section = { title: string; body?: string; list?: string[] };

function buildSections(b: StartupBlueprint): Section[] {
  const swot = b.swotAnalysis ?? { strengths: [], weaknesses: [], opportunities: [], threats: [] };
  const swotBody = [
    `Strengths:\n${asList(swot.strengths).map(s => `• ${s}`).join("\n") || "—"}`,
    `Weaknesses:\n${asList(swot.weaknesses).map(s => `• ${s}`).join("\n") || "—"}`,
    `Opportunities:\n${asList(swot.opportunities).map(s => `• ${s}`).join("\n") || "—"}`,
    `Threats:\n${asList(swot.threats).map(s => `• ${s}`).join("\n") || "—"}`,
  ].join("\n\n");

  return [
    { title: "Executive Summary", body: asText(b.elevatorPitch) },
    { title: "Problem", body: asText(b.problemStatement) },
    { title: "Solution", body: asText(b.solution) },
    { title: "Target Audience", body: asText(b.targetAudience) },
    { title: "Customer Persona", body: asText(b.customerPersona) },
    { title: "Market Opportunity", body: asText(b.marketOpportunity) },
    { title: "Competitor Analysis", body: asText(b.competitorAnalysis) },
    { title: "Unique Value Proposition", body: asText(b.uniqueSellingProposition) },
    { title: "SWOT Analysis", body: swotBody },
    { title: "Business Model", body: asText(b.businessModel) },
    { title: "Revenue Streams", body: asText(b.revenueModel) },
    { title: "Pricing Strategy", body: asText(b.pricingSuggestions) },
    { title: "Estimated Startup Cost", body: asText(b.estimatedStartupCost) },
    { title: "Branding Strategy", body: asText(b.brandingStrategy) },
    { title: "Brand Identity", body: asText(b.brandIdentity) },
    { title: "Logo Concept", body: asText(b.logoConcept) },
    { title: "Color Palette", list: asList(b.colorPalette) },
    { title: "Marketing Strategy", body: asText(b.marketingStrategy) },
    { title: "Implementation Roadmap", body: asText(b.launchRoadmap) },
    { title: "Financial Estimate", body: asText(b.financialEstimate) },
    { title: "Risk Analysis", list: asList(b.risks) },
    { title: "Growth Opportunities", list: asList(b.growthOpportunities) },
    { title: "Investor Pitch Summary", body: asText(b.investorPitchSummary) },
    { title: "AI Recommendations", list: asList(b.recommendations) },
    { title: "Launch Checklist / Next Steps", list: asList(b.nextSteps) },
  ].filter(s => (s.body && s.body.trim()) || (s.list && s.list.length));
}

export function buildMarkdown(b: StartupBlueprint, meta: ReportMeta): string {
  const lines: string[] = [];
  lines.push(`# ${meta.name || b.startupName || "Startup Report"}`);
  if (b.tagline) lines.push(`_${b.tagline}_`);
  lines.push("");
  lines.push(`**Generated:** ${fmtDate(meta.createdAt)}  `);
  if (meta.score != null) lines.push(`**Startup Score:** ${meta.score}/100  `);
  lines.push(`**Generated by:** FoundrIQ AI`);
  lines.push("");
  for (const s of buildSections(b)) {
    lines.push(`## ${s.title}`);
    if (s.body) lines.push(s.body);
    if (s.list?.length) for (const item of s.list) lines.push(`- ${item}`);
    lines.push("");
  }
  lines.push("---");
  lines.push("_AI Final Recommendation: Validate with 10+ target customers before committing capital._");
  lines.push("_Generated by FoundrIQ AI_");
  return lines.join("\n");
}

export function buildPlainText(b: StartupBlueprint, meta: ReportMeta): string {
  // Human-readable text version for clipboard.
  return buildMarkdown(b, meta)
    .replace(/^#+\s*/gm, "")
    .replace(/[_*`]/g, "");
}

export function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function safeFilename(name: string, ext: string): string {
  const base = (name || "startup-report").trim().replace(/[^\w\-]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
  return `${base || "startup-report"}.${ext}`;
}

/* ---------------- PDF generation ---------------- */

export async function generatePdf(b: StartupBlueprint, meta: ReportMeta): Promise<Blob> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 56;
  const contentW = pageW - margin * 2;
  const title = meta.name || b.startupName || "Startup Report";
  const genDate = fmtDate(meta.createdAt);

  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - margin - 24) {
      doc.addPage();
      y = margin;
    }
  };

  const writeParagraph = (text: string, opts: { size?: number; bold?: boolean; color?: [number, number, number]; gap?: number } = {}) => {
    const { size = 11, bold = false, color = [30, 30, 40], gap = 6 } = opts;
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, contentW) as string[];
    const lineH = size * 1.35;
    for (const line of lines) {
      ensureSpace(lineH);
      doc.text(line, margin, y);
      y += lineH;
    }
    y += gap;
  };

  const writeHeading = (text: string) => {
    ensureSpace(40);
    y += 6;
    doc.setDrawColor(120, 90, 220);
    doc.setLineWidth(2);
    doc.line(margin, y, margin + 32, y);
    y += 14;
    writeParagraph(text, { size: 15, bold: true, color: [30, 30, 60], gap: 8 });
  };

  /* Cover page */
  doc.setFillColor(15, 15, 30);
  doc.rect(0, 0, pageW, pageH, "F");
  doc.setTextColor(230, 230, 245);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("FOUNDRIQ AI", margin, margin);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(180, 180, 210);
  doc.text("Startup Blueprint Report", margin, margin + 14);

  doc.setTextColor(240, 240, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(30);
  const titleLines = doc.splitTextToSize(title, contentW) as string[];
  let ty = pageH / 2 - titleLines.length * 18;
  for (const l of titleLines) {
    doc.text(l, margin, ty);
    ty += 34;
  }
  if (b.tagline) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(14);
    doc.setTextColor(190, 190, 220);
    const tag = doc.splitTextToSize(b.tagline, contentW) as string[];
    for (const l of tag) {
      doc.text(l, margin, ty);
      ty += 20;
    }
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(180, 180, 210);
  doc.text(`Generated: ${genDate}`, margin, pageH - margin - 30);
  if (meta.score != null) doc.text(`Startup Score: ${meta.score}/100`, margin, pageH - margin - 14);
  doc.text("Generated by FoundrIQ AI", pageW - margin, pageH - margin - 14, { align: "right" });

  /* Content pages */
  doc.addPage();
  y = margin;
  doc.setTextColor(30, 30, 40);

  writeParagraph(title, { size: 20, bold: true, gap: 4 });
  if (b.tagline) writeParagraph(b.tagline, { size: 12, color: [110, 110, 130], gap: 10 });
  writeParagraph(`Generated ${genDate}${meta.score != null ? `  ·  Score ${meta.score}/100` : ""}`, {
    size: 9,
    color: [130, 130, 150],
    gap: 14,
  });

  for (const s of buildSections(b)) {
    writeHeading(s.title);
    if (s.body) writeParagraph(s.body, { size: 11, gap: 8 });
    if (s.list?.length) {
      for (const item of s.list) {
        writeParagraph(`•  ${item}`, { size: 11, gap: 2 });
      }
      y += 6;
    }
  }

  /* Page numbers + footer */
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 160);
    if (i > 1) {
      doc.text(`${title}  ·  FoundrIQ AI`, margin, pageH - 24);
      doc.text(`Page ${i} of ${total}`, pageW - margin, pageH - 24, { align: "right" });
    }
  }

  return doc.output("blob");
}
